apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-nginx
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://DE4D11BDF16A21EF3C4691F50475B7DA.gr7.ap-southeast-2.eks.amazonaws.com' #Replace the API endpint URL of your EKS cluster
  source:
    path: workload/aws-eks
    repoURL: 'https://github.com/maiconrocha/eks-ec2-clusterapi-gitops' #Indicate which source repo for fetching the cluster configuration
    targetRevision: HEAD
  project: default #You can give a project name here
  syncPolicy:
    automated:
      allowEmpty: true
